// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClPY8jkp12xGc5JovoF3U78xG1wqh0oEA',
    appId: '1:88097674888:web:b3a3ca355655bd2b49b13d',
    messagingSenderId: '88097674888',
    projectId: 'jamtalkie---dev',
    authDomain: 'jamtalkie---dev.firebaseapp.com',
    storageBucket: 'jamtalkie---dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0nLfQ3Viyve1PapUBWGiuODHxogOum3o',
    appId: '1:88097674888:android:04d29088175f259349b13d',
    messagingSenderId: '88097674888',
    projectId: 'jamtalkie---dev',
    storageBucket: 'jamtalkie---dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLxGoocSpzDaCjEZeIpUyPv_uG5yZXsA',
    appId: '1:88097674888:ios:4189fd070951fe5249b13d',
    messagingSenderId: '88097674888',
    projectId: 'jamtalkie---dev',
    storageBucket: 'jamtalkie---dev.appspot.com',
    iosClientId:
        '88097674888-krijt6bhpmcbbm7b0si1gc7uh0bdblrh.apps.googleusercontent.com',
    iosBundleId: 'com.athenia.jamtalkie',
  );
}
